import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "normalize.css";
import "@/styles/globals.scss";
import GlobalProvider from "@/redux/GlobalProvider";
import Header from '@/components/client/header'
import Footer from '@/components/client/footer'
import Category from '@/components/client/Category'
import 'bootstrap/dist/css/bootstrap.min.css'
import Container from 'react-bootstrap/Container'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalProvider>
          <Header />
          <Category />
          <Container>
            {children}
          </Container>
          <Footer />
        </GlobalProvider>
      </body>
    </html>
  );
}
